--- #YAML:1.0
name:               Protocol-Redis
version:            0.9002
abstract:           Redis protocol parser/encoder with asynchronous capabilities.
author:
    - Sergey Zasenko <undef@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0.88
requires:
    Carp:        0
    List::Util:  0
resources:
    repository:  http://github.com/und3f/protocol-redis
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
